export const getSatelliteData = () => {
    return [
        {
                "STT": "1",
                "Tên": "888",
                "Địa chỉ": "Quảng Xương, Thanh Hóa",
                "SL chuyền": "20",
                "Lao động": "550",
                "SL LĐ/chuyền": "28",
                "Chủng loại SP": "Blazer, Jacket 3 lớp, quần Golf",
                "Khách hàng": "T-Concepts, FYI, Lever TCT, Suzhou",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "",
                "Điều khoản thanh toán": "TT sau 30 ngày.",
                "Liên hệ": "Mr Lâm - 0914899493",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "2",
                "Tên": "AM",
                "Địa chỉ": "Sài Đồng",
                "SL chuyền": "2",
                "Lao động": "60",
                "SL LĐ/chuyền": "30",
                "Chủng loại SP": "Hàng đơn giản",
                "Khách hàng": "Vaude",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "",
                "Điều khoản thanh toán": "TT sau 30 ngày",
                "Liên hệ": "Mrs Hương - 0912214896",
                "Ghi chú": "Có thể cân nhắc với điều kiện QA May 10 thường trực tại nhà máy",
                "Đính kèm": ""
        },
        {
                "STT": "3",
                "Tên": "An Phát",
                "Địa chỉ": "",
                "SL chuyền": "6",
                "Lao động": "180",
                "SL LĐ/chuyền": "30",
                "Chủng loại SP": "Váy, đầm",
                "Khách hàng": "Snowcoats",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "",
                "Điều khoản thanh toán": "TT sau 30 ngày sau giao hàng",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "4",
                "Tên": "Atexims",
                "Địa chỉ": "",
                "SL chuyền": "4",
                "Lao động": "150",
                "SL LĐ/chuyền": "38",
                "Chủng loại SP": "Jacket bông nhồi, bông tấm, quần",
                "Khách hàng": "ASM",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "Inditex",
                "Điều khoản thanh toán": "TT sau 30 ngày",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "5",
                "Tên": "Bắc Hà",
                "Địa chỉ": "",
                "SL chuyền": "5",
                "Lao động": "250",
                "SL LĐ/chuyền": "50",
                "Chủng loại SP": "Jacket bông",
                "Khách hàng": "ASM",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "BSCI",
                "Điều khoản thanh toán": "TT sau 30 ngày",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "6",
                "Tên": "Bắc Hà",
                "Địa chỉ": "",
                "SL chuyền": "5",
                "Lao động": "250",
                "SL LĐ/chuyền": "50",
                "Chủng loại SP": "Jacket (chần, lông vũ, bông nhồi), quần",
                "Khách hàng": "Collin",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "",
                "Điều khoản thanh toán": "TT sau 45 ngày, nhưng ngay sau khi giao hàng Bắc Hà sẽ ĐN tạm ứng 50%",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "7",
                "Tên": "Bảo Hân",
                "Địa chỉ": "",
                "SL chuyền": "3",
                "Lao động": "90",
                "SL LĐ/chuyền": "30",
                "Chủng loại SP": "Jacket, váy, đầm",
                "Khách hàng": "Newtimes",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "",
                "Điều khoản thanh toán": "TT sau 15 ngày sau giao hàng",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "8",
                "Tên": "BTM",
                "Địa chỉ": "",
                "SL chuyền": "14",
                "Lao động": "322",
                "SL LĐ/chuyền": "23",
                "Chủng loại SP": "Hàng dệt kim",
                "Khách hàng": "Hangten",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "",
                "Điều khoản thanh toán": "TT sau 30 ngày sau giao hàng",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "9",
                "Tên": "Chi Anh",
                "Địa chỉ": "",
                "SL chuyền": "3",
                "Lao động": "90",
                "SL LĐ/chuyền": "30",
                "Chủng loại SP": "Quần, jacket mỏng",
                "Khách hàng": "Lever - STF",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "",
                "Điều khoản thanh toán": "TT trước",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "10",
                "Tên": "Công ty Cổ phần May 199",
                "Địa chỉ": "",
                "SL chuyền": "4",
                "Lao động": "200",
                "SL LĐ/chuyền": "50",
                "Chủng loại SP": "jacket 3 lớp, lông vũ, bông nhồi",
                "Khách hàng": "ASM, ESP, PRIMARY",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "k có",
                "Điều khoản thanh toán": "TT sau 30 ngày.",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "11",
                "Tên": "Công ty Cổ phần May Kim Động",
                "Địa chỉ": "",
                "SL chuyền": "10",
                "Lao động": "300",
                "SL LĐ/chuyền": "30",
                "Chủng loại SP": "jacket 3 lớp (bông nhồi, lông vũ…)",
                "Khách hàng": "ESP, JADAMS",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "Inditex, Mango",
                "Điều khoản thanh toán": "TT sau 30 ngày.",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "12",
                "Tên": "Đáp Cầu",
                "Địa chỉ": "",
                "SL chuyền": "100",
                "Lao động": "5000",
                "SL LĐ/chuyền": "50",
                "Chủng loại SP": "Jacket (chần, lông vũ, bông nhồi), quần",
                "Khách hàng": "Collin",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "Better Work, Wrap",
                "Điều khoản thanh toán": "TT sau 45 ngày",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "13",
                "Tên": "Đạt Đăng",
                "Địa chỉ": "",
                "SL chuyền": "4",
                "Lao động": "200",
                "SL LĐ/chuyền": "50",
                "Chủng loại SP": "Jacket bông nhồi, bông tấm, quần",
                "Khách hàng": "ASM",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "Chưa có đánh giá",
                "Điều khoản thanh toán": "TT sau 30 ngày",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "14",
                "Tên": "Đông Thắng",
                "Địa chỉ": "",
                "SL chuyền": "5",
                "Lao động": "115",
                "SL LĐ/chuyền": "23",
                "Chủng loại SP": "Hàng đơn giản",
                "Khách hàng": "Collin",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "",
                "Điều khoản thanh toán": "TT sau 45 ngày",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "15",
                "Tên": "Đức Mạnh",
                "Địa chỉ": "",
                "SL chuyền": "6",
                "Lao động": "300",
                "SL LĐ/chuyền": "50",
                "Chủng loại SP": "Jacket 3 lớp, Jacket bông nhồi, Jacket bông tấm",
                "Khách hàng": "ASM",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "Inditex; đang đánh giá BSCI",
                "Điều khoản thanh toán": "TT sau 30 ngày kể từ ngày xuất hàng",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "16",
                "Tên": "Garnet Nam Định",
                "Địa chỉ": "",
                "SL chuyền": "5",
                "Lao động": "250",
                "SL LĐ/chuyền": "50",
                "Chủng loại SP": "Jacket (chần, lông vũ, bông nhồi), quần",
                "Khách hàng": "ASM",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "Better work, BSCI",
                "Điều khoản thanh toán": "TT sau 30 ngày.",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "17",
                "Tên": "Hồ Gươm",
                "Địa chỉ": "",
                "SL chuyền": "12",
                "Lao động": "360",
                "SL LĐ/chuyền": "30",
                "Chủng loại SP": "Quần, áo jacket bông nhồi, bông chần.",
                "Khách hàng": "ASM",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "",
                "Điều khoản thanh toán": "TT sau 30 ngày",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "18",
                "Tên": "Maxport",
                "Địa chỉ": "",
                "SL chuyền": "15",
                "Lao động": "750",
                "SL LĐ/chuyền": "50",
                "Chủng loại SP": "jacket 3 lớp , bông nhồi, bông tấm, quần",
                "Khách hàng": "ASM",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "Lululemon, Nike.",
                "Điều khoản thanh toán": "TT sau 30 ngày.",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "19",
                "Tên": "May Hưng Long",
                "Địa chỉ": "Mỹ Hào, Hưng Yên",
                "SL chuyền": "30",
                "Lao động": "1900",
                "SL LĐ/chuyền": "63",
                "Chủng loại SP": "Jacket 1 lớp, Jacket 2 lớp, Jacket bông, Lông vũ, Hàng ép seam, Áo bra, Boxer, Underwear, Quần bơi",
                "Khách hàng": "Tommy, Colombia, Nike, Walmart, The North Face",
                "Thời gian làm việc": "7h30 đến 18h30",
                "Dò kim": "Có",
                "Phòng hút ẩm": "Có",
                "Chỗ nghỉ QC": "Có",
                "Điều hòa": "Toàn bộ",
                "Chứng chỉ": "WRAP",
                "Điều khoản thanh toán": "",
                "Liên hệ": "",
                "Ghi chú": "Áo Tommy lông vũ 250 / 45 LĐ, giá 7$ sll\n12 triệu bao gồm lương tháng 13",
                "Đính kèm": "https://1drv.ms/f/c/63f0eec287e5ac0e/EvxgIX9K0tFInzxasSptN5YBpKHjDJJ6l7G_kjhKanVWmQ?e=offsf2"
        },
        {
                "STT": "20",
                "Tên": "QTNP",
                "Địa chỉ": "Bắc Giang",
                "SL chuyền": "12",
                "Lao động": "360",
                "SL LĐ/chuyền": "30",
                "Chủng loại SP": "Quần, Jacket bông",
                "Khách hàng": "Chubbies, Quicksilver",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "BSCI, GRS, HIGG",
                "Điều khoản thanh toán": "TT sau 20 ngày",
                "Liên hệ": "A Phong - 0904781168",
                "Ghi chú": "Có 15 máy lập trình, giá tương đương range giá May 10",
                "Đính kèm": ""
        },
        {
                "STT": "21",
                "Tên": "Shinwoon",
                "Địa chỉ": "",
                "SL chuyền": "",
                "Lao động": "",
                "SL LĐ/chuyền": "",
                "Chủng loại SP": "Hàng dệt kim",
                "Khách hàng": "ASM",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "Wrap, BSCI, Better work",
                "Điều khoản thanh toán": "TT sau 10 ngày giao hàng, riêng lô  cuối cùng tt trước khi xuất hàng",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "22",
                "Tên": "Tâm Việt",
                "Địa chỉ": "",
                "SL chuyền": "12",
                "Lao động": "500",
                "SL LĐ/chuyền": "42",
                "Chủng loại SP": "Jacket 2 lớp, Jacket 3 lớp, Jacket bông",
                "Khách hàng": "ASM",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "SA8000",
                "Điều khoản thanh toán": "TT sau 30 ngày",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "23",
                "Tên": "Tâm Việt",
                "Địa chỉ": "",
                "SL chuyền": "15",
                "Lao động": "",
                "SL LĐ/chuyền": "",
                "Chủng loại SP": "Jacket (chần, lông vũ, bông nhồi), quần",
                "Khách hàng": "Collin",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "SA8000",
                "Điều khoản thanh toán": "TT sau 30 ngày",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "24",
                "Tên": "Tân Tiến",
                "Địa chỉ": "Bắc Giang",
                "SL chuyền": "",
                "Lao động": "",
                "SL LĐ/chuyền": "",
                "Chủng loại SP": "Jacket bông",
                "Khách hàng": "Tom Tailor",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "",
                "Điều khoản thanh toán": "TT sau 20 ngày",
                "Liên hệ": "c Yến - 0916741798",
                "Ghi chú": "Quen làm hàng ASM; ưu tiên những mã jacket bông đơn giản số lượng lớn ; ko thích làm đơn hàng số lượng nhỏ. Cần thanh toán tiền đúng hạn",
                "Đính kèm": ""
        },
        {
                "STT": "25",
                "Tên": "Thiên Sơn - Ý Linh",
                "Địa chỉ": "",
                "SL chuyền": "12",
                "Lao động": "500",
                "SL LĐ/chuyền": "42",
                "Chủng loại SP": "Knit",
                "Khách hàng": "ASM",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "Wrap, HBI",
                "Điều khoản thanh toán": "TT sau 30 ngày",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "26",
                "Tên": "Tiên Sơn",
                "Địa chỉ": "Thanh Hóa",
                "SL chuyền": "13",
                "Lao động": "455",
                "SL LĐ/chuyền": "35",
                "Chủng loại SP": "Jacket bông tấm, Áo dạ, Hàng dệt kim",
                "Khách hàng": "DSI",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "Grs, Wrap, ISO 901, Higg",
                "Điều khoản thanh toán": "TT sau 15 ngày",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "27",
                "Tên": "Tiến Thành",
                "Địa chỉ": "",
                "SL chuyền": "2",
                "Lao động": "60",
                "SL LĐ/chuyền": "30",
                "Chủng loại SP": "Hàng đơn giản",
                "Khách hàng": "Collin",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "",
                "Điều khoản thanh toán": "TT sau 15 ngày sau khi nhận được tiền của khách",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "28",
                "Tên": "Toàn Anh",
                "Địa chỉ": "",
                "SL chuyền": "12",
                "Lao động": "500",
                "SL LĐ/chuyền": "42",
                "Chủng loại SP": "Jacket 1 lớp, Jacket 2 lớp",
                "Khách hàng": "ASM",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "",
                "Điều khoản thanh toán": "TT trước",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "29",
                "Tên": "Toàn Bích",
                "Địa chỉ": "Nam Định",
                "SL chuyền": "6",
                "Lao động": "300",
                "SL LĐ/chuyền": "50",
                "Chủng loại SP": "Jacket 3 lớp, Jacket bông nhồi, Jacket lông vũ, Quần",
                "Khách hàng": "Tom Tailor, Mainpol",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "",
                "Điều khoản thanh toán": "TT sau 30 ngày.",
                "Liên hệ": "A Toàn - 0946676890",
                "Ghi chú": "Giá phải chăng; làm hàng số lượng nhỏ ko upcharge cao",
                "Đính kèm": ""
        },
        {
                "STT": "30",
                "Tên": "Veston Thiệu Đô",
                "Địa chỉ": "Thiệu Hóa - Thanh Hóa",
                "SL chuyền": "3",
                "Lao động": "250",
                "SL LĐ/chuyền": "83",
                "Chủng loại SP": "Veston",
                "Khách hàng": "Mitsui",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "",
                "Điều khoản thanh toán": "TT sau 30 ngày.",
                "Liên hệ": "Nguyệt - 0943350808",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "31",
                "Tên": "Việt Thái",
                "Địa chỉ": "",
                "SL chuyền": "23",
                "Lao động": "900",
                "SL LĐ/chuyền": "39",
                "Chủng loại SP": "Jacket bông nhồi, bông tấm, hàng dán seam",
                "Khách hàng": "ASM",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "Better work, BSCI, Wrap.",
                "Điều khoản thanh toán": "TT sau 30 ngày",
                "Liên hệ": "",
                "Ghi chú": "",
                "Đính kèm": ""
        },
        {
                "STT": "32",
                "Tên": "Vĩnh Oanh",
                "Địa chỉ": "Ý Yên - Nam Định ",
                "SL chuyền": "8",
                "Lao động": "500",
                "SL LĐ/chuyền": "63",
                "Chủng loại SP": "Jacket bông, quần",
                "Khách hàng": "Chubbies",
                "Thời gian làm việc": "",
                "Dò kim": "",
                "Phòng hút ẩm": "",
                "Chỗ nghỉ QC": "",
                "Điều hòa": "",
                "Chứng chỉ": "ISO 9001",
                "Điều khoản thanh toán": "TT sau 20 ngày",
                "Liên hệ": "A Lâm - 0988880702",
                "Ghi chú": "Chất lượng từ may đến đóng gói ko ổn phù hợp làm những hàng đồng phục ",
                "Đính kèm": ""
        }
];
};
