export const getSatelliteData = () => {
    return [
        {
            "STT": "1",
            "Tên": "888",
            "Địa chỉ": "Quảng Xương, Thanh Hóa",
            "SL chuyền": "20",
            "Lao động": "550",
            "SLLĐ/chuyền": "27.5",
            "Chủng loại SP": "Blazer, Jacket 3 lớp, quần Golf",
            "Khách hàng": "T-Concepts, FYI, Lever TCT, Suzhou",
            "Thời gian làm việc": "",
            "Dò kim": "",
            "Phòng hút ẩm": "",
            "Chỗ nghỉ QC": "",
            "Điều hòa": "",
            "Chứng chỉ": "",
            "Điều khoản thanh toán": "TT sau 30 ngày.",
            "Liên hệ": "Mr Lâm - 0914899493",
            "Ghi chú": "",
            "Đính kèm": ""
        },
        {
            "STT": "2",
            "Tên": "AM",
            "Địa chỉ": "Sài Đồng",
            "SL chuyền": "2",
            "Lao động": "60",
            "SLLĐ/chuyền": "30",
            "Chủng loại SP": "hàng đơn giản, tổ hợp",
            "Khách hàng": "Vaude",
            "Thời gian làm việc": "",
            "Dò kim": "",
            "Phòng hút ẩm": "",
            "Chỗ nghỉ QC": "",
            "Điều hòa": "",
            "Chứng chỉ": "",
            "Điều khoản thanh toán": "TT sau 30 ngày",
            "Liên hệ": "Mrs Hương - 0912214896",
            "Ghi chú": "Có thể cân nhắc với điều kiện QA May 10 thường trực tại nhà máy",
            "Đính kèm": ""
        },
        {
            "STT": "3",
            "Tên": "An Phát",
            "Địa chỉ": "",
            "SL chuyền": "6",
            "Lao động": "180",
            "SLLĐ/chuyền": "30",
            "Chủng loại SP": "Váy, đầm",
            "Khách hàng": "Snowcoats",
            "Thời gian làm việc": "",
            "Dò kim": "",
            "Phòng hút ẩm": "",
            "Chỗ nghỉ QC": "",
            "Điều hòa": "",
            "Chứng chỉ": "",
            "Điều khoản thanh toán": "TT sau 30 ngày sau giao hàng",
            "Liên hệ": "",
            "Ghi chú": "",
            "Đính kèm": ""
        },
        {
            "STT": "4",
            "Tên": "Atexims",
            "Địa chỉ": "",
            "SL chuyền": "4",
            "Lao động": "150",
            "SLLĐ/chuyền": "37.5",
            "Chủng loại SP": "Jacket bông nhồi, bông tấm, quần",
            "Khách hàng": "ASM",
            "Thời gian làm việc": "",
            "Dò kim": "",
            "Phòng hút ẩm": "",
            "Chỗ nghỉ QC": "",
            "Điều hòa": "",
            "Chứng chỉ": "Inditex",
            "Điều khoản thanh toán": "TT sau 30 ngày",
            "Liên hệ": "",
            "Ghi chú": "",
            "Đính kèm": ""
        },
        {
            "STT": "5",
            "Tên": "Bắc Hà",
            "Địa chỉ": "",
            "SL chuyền": "5",
            "Lao động": "250",
            "SLLĐ/chuyền": "50",
            "Chủng loại SP": "Jacket bông",
            "Khách hàng": "ASM",
            "Thời gian làm việc": "",
            "Dò kim": "",
            "Phòng hút ẩm": "",
            "Chỗ nghỉ QC": "",
            "Điều hòa": "",
            "Chứng chỉ": "BSCI",
            "Điều khoản thanh toán": "TT sau 30 ngày",
            "Liên hệ": "",
            "Ghi chú": "",
            "Đính kèm": ""
        },
        {
            "STT": "6",
            "Tên": "Bắc Hà",
            "Địa chỉ": "",
            "SL chuyền": "5",
            "Lao động": "250",
            "SLLĐ/chuyền": "50",
            "Chủng loại SP": "Jacket (chần, lông vũ, bông nhồi), quần",
            "Khách hàng": "Collin",
            "Thời gian làm việc": "",
            "Dò kim": "",
            "Phòng hút ẩm": "",
            "Chỗ nghỉ QC": "",
            "Điều hòa": "",
            "Chứng chỉ": "",
            "Điều khoản thanh toán": "TT sau 45 ngày, nhưng ngay sau khi giao hàng Bắc Hà sẽ ĐN tạm ứng 50%",
            "Liên hệ": "",
            "Ghi chú": "",
            "Đính kèm": ""
        }
    ];
};
